; Do not delete this line.
;  Avoid using first line what there is UTF-8 BOM.

[Profile]
; 배포환경
; "config.<env>.ini" 파일을 불러온다.
Env = local

; 설정파일에서 IP 주소 등을 읽는데 사용한다.
; 기본값은 실행파일명
Service =

; 동일 서비스 간 식별자
; 단일지점 서비스는 사용하지 않는다.
Id = 1
